sudo: false

language: node_js
node_js:
  - latest

cache:
  directories:
    - node_modules

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - semantic-release pre
  - npm publish
  - semantic-release post

branches:
  only:
    - master
