sudo: false

language: node_js
node_js:
  - 7

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - semantic-release pre
  - npm publish --access public
  - semantic-release post

branches:
  only:
    - master
